#!/bin/bash
# backup-db: Backup a database.

command -v mysql >/dev/null 2>&1 || { echo "I require mysql but it's not installed.  Aborting." >&2; exit 1; }
command -v mysqldump >/dev/null 2>&1 || { echo "I require mysqldump but it's not installed.  Aborting." >&2; exit 1; }

if [[ ! -e "${BASH_SOURCE%/*}/db.conf" ]]; then
    echo "Configuration file missing. We just copied the example for you."
    echo "Edit the db.conf file and re-run script."
    cp "${BASH_SOURCE%/*}/db.conf.example" "${BASH_SOURCE%/*}/db.conf"
  exit 1;
fi

. "${BASH_SOURCE%/*}/db.conf"

if [ -z "$1" ]; then
  echo "backup-db [source]";
  echo "";
  echo -e "\tsource\t\t- The source database (from list)";
  mysql_config_editor print --all
  echo "";
  exit 1;
fi

SOURCE_DB=$1

MYSQL_CMD="mysql --login-path=$SOURCE_DB -e \";\""

if [ ! $MYSQL_CMD 2>/dev/null ]; then
    echo "Incorrect MySQL login details for '$SOURCE_DB'"
    echo ""
    exit 1;
fi

DATE=`date +%Y%m%d_%H%M%S`

# Backup destination
mkdir -p "./backups/saved"
mysqldump --login-path=$SOURCE_DB --add-drop-table $SOURCE_DB > "./backups/saved/TEMP_${SOURCE_DB}_$DATE.sql"
perl -pe 's/\sDEFINER=`[^`]+`@`[^`]+`//' < "./backups/saved/TEMP_${SOURCE_DB}_$DATE.sql" > "./backups/saved/${SOURCE_DB}_$DATE.sql"
unlink "./backups/saved/TEMP_${SOURCE_DB}_$DATE.sql" > /dev/null 2>&1

echo "./backups/saved/${SOURCE_DB}_$DATE.sql"
